# Function that uses geocoding to extract latitude-longitude using address or zip-code:

In [1]:
with open('apikey.txt') as f:
    api_key = f.readline()
    f.close

In [2]:
import requests
GMAPS_API_KEY = api_key

In [3]:
def get_lat_long(address_or_zipcode):
    """
    This function can be used to extract the latitudinal and longitudinal
    coordinated of an entered address {as a string} or an entered zipcode 
    {as a number} and return (Latitude, Longitude)
    """

    lat, lng = None, None
    api_key = GMAPS_API_KEY
    
    # Setting up a base URL and an f-string to capture the position
    # Using the address and the API key
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    position = f"{base_url}?address={address_or_zipcode}&key={api_key}"
    
    # Requesting that position from GoogleMaps
    r = requests.get(position)
    
    # If status code is not in valid range (ex. 404 - Not Found)
    # Return without extracting latitude-longitude information
    if r.status_code not in range(200, 299):
        return None, None
    
    # Otherwise extract the latitude-longitude information from the request response
    try:
        results = r.json()['results'][0]
        lat = results['geometry']['location']['lat']
        lng = results['geometry']['location']['lng']
    except:
        pass
    
    return lat, lng

In [4]:
address = 'Ogg Residence Hall, Madison, Wisconsin'
get_lat_long(address)

(43.070549, -89.399936)

In [5]:
address = "Greenwich, London"
get_lat_long(address)

(51.4933675, 0.0098214)

In [6]:
address = "Berlin, Germany"
get_lat_long(address)

(52.52000659999999, 13.404954)

In [7]:
address = "Cheesecake Factory, West Towne Mall, Madison, Wisconsin, USA"
get_lat_long(address)

(43.057573, -89.5048796)

In [8]:
import pandas as pd
data = pd.read_csv('cleaned_df.csv')
data

,IncidentID,IncidentType,CaseNumber,Suspect,Arrested,Address,Victim,Details,ReleasedBy,Day,Month,Year,Hour
0,7400,Assist Outside Agency,2005-13680 ...,NaN,...,"700 Block of E. Washington Ave., Madison, Wisc...",...,On 2/6/05 at approximately 10:33 p.m. Officer ...,Mike Hanson,7,10,2005,4
1,7401,Arrested Person,2005-22647 ...,NaN,"Tony R Markovitch, 20 years old, 301 Knutson D...","First St & E Washington Ave, Madison, Wisconsin",n/a ...,"At approximately 11:42 pm, an officer noted a ...",Lt Pat Malloy,3,3,2005,6
2,7402,Arrested Person,2005-22345 ...,NaN,Martell D. Britton m/b 05-03-85\r\r\nCharge: ...,"8 New Berm Court, Madison, Wisconsin",Home Depot ...,"On 03/02/2005 at approximately 8:15 am, the Ma...",Lt. T. Peterson,2,3,2005,15
3,7403,Arrested Person,2005-22688 ...,NaN,"Twainesse L Peavy, 26 yrs old, 2317 Fish Hatch...","4300 Lumley Rd, Madison, Wisconsin",Adult male resident of Madison ...,"At approximately 7:30 am this date, Officers r...",Lt. Pat Malloy,3,3,2005,14
4,7404,Information,2005-999999 ...,NaN,...,"211 S. Carroll Street, Madison, Wisconsin",...,DELIVERY NOTICES FOR UNPAID PARKING TICKETS\r\...,Lieutenant Joe Balles,4,3,2005,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14131,28608,Robbery,2021-410423,"Male described as 6 feet tall, slender, with a...",NaN,"3700 Frosted Leaf Dr, Madison, Wisconsin",NaN,Madison Police officers were dispatched to the...,Lt. Michael Richardson,12,10,2021,7
14132,28609,Attempted Homicide,2021-407981,NaN,Tokiee D. Sole,"5800 block Balsam Rd, Madison, Wisconsin",NaN,"On 10/10/2021 at approximately 3:50 a.m., Madi...",P.O. Hunter Lisko,10,10,2021,9
14133,28610,Information,2021-411747,NaN,NaN,"Esker Trl/Lilyview Ln, Madison, Wisconsin",NaN,"On October 12th, 2021 at approximately 6:43 PM...",PIO Julie Laundrie,12,10,2021,24
14134,28611,Fight (In Progress),2021-412832,NaN,"Aaron Mixon, 24-year-old\r\n\r\nNathan Dougher...","200 N First St, Madison, Wisconsin",NaN,Madison Police Officers responded to 200 N Fir...,P.O. Ryan Kimberley,13,10,2021,22
14135,28612,Information,0000-000000,NaN,NaN,"1710 Mckenna Blvd, Madison, Wisconsin",NaN,The Madison Police Department’s West District ...,P.O. Ryan Kimberley,14,10,2021,5

In [9]:
import numpy as np
data['Lat'] = pd.Series(np.zeros(data.shape[0]))
data['Long'] = pd.Series(np.zeros(data.shape[0]))

for i in range(df.shape[0]):
    
    address = df['Address'][i]
    
    df['Lat'][i] = get_lat_long(address)
    df['Long'][i] = get_lat_long(address)